apiVersion: v1
kind: Pod
metadata:
  name: lms-us-mk1
spec:
  containers:
  - name: lms-us-mk1
    image: lms-userservice
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8079
