apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-usr-ks1
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: lms-usr-ks1
        image: lms-userservice
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8082
